export enum UserRole {
  ADMIN = 'ADMIN',
  SALES_REP = 'SALES_REP',
}

export enum LeadStatus {
  NEW = 'NEW',
  READY_TO_CALL = 'READY_TO_CALL',
  CALLING = 'CALLING',
  CONTACTED = 'CONTACTED',
  QUALIFIED = 'QUALIFIED',
  UNQUALIFIED = 'UNQUALIFIED',
  CALLBACK_REQUESTED = 'CALLBACK_REQUESTED',
  MEETING_BOOKED = 'MEETING_BOOKED',
  DO_NOT_CALL = 'DO_NOT_CALL',
  CONVERTED = 'CONVERTED',
  LOST = 'LOST',
}

export enum PipelineStage {
  NEW_LEAD = 'NEW_LEAD',
  DISCOVERY = 'DISCOVERY',
  QUALIFIED = 'QUALIFIED',
  DEMO_BOOKED = 'DEMO_BOOKED',
  PROPOSAL = 'PROPOSAL',
  NEGOTIATION = 'NEGOTIATION',
  WON = 'WON',
  LOST = 'LOST',
}

export enum CampaignStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
}

export enum CampaignLeadStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  CALLED = 'CALLED',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
  FAILED = 'FAILED',
}

export enum CallDirection {
  OUTBOUND = 'OUTBOUND',
  INBOUND = 'INBOUND',
}

export enum CallStatus {
  QUEUED = 'QUEUED',
  RINGING = 'RINGING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
  NO_ANSWER = 'NO_ANSWER',
  BUSY = 'BUSY',
  VOICEMAIL = 'VOICEMAIL',
}

export enum CallOutcome {
  MEETING_BOOKED = 'MEETING_BOOKED',
  QUALIFIED_NO_MEETING = 'QUALIFIED_NO_MEETING',
  CALLBACK_REQUESTED = 'CALLBACK_REQUESTED',
  NOT_INTERESTED = 'NOT_INTERESTED',
  NOT_QUALIFIED = 'NOT_QUALIFIED',
  WRONG_PERSON = 'WRONG_PERSON',
  VOICEMAIL = 'VOICEMAIL',
  NO_ANSWER = 'NO_ANSWER',
  BUSY = 'BUSY',
  FAILED = 'FAILED',
  DO_NOT_CALL = 'DO_NOT_CALL',
  TRANSFERRED_TO_HUMAN = 'TRANSFERRED_TO_HUMAN',
  FOLLOW_UP_REQUIRED = 'FOLLOW_UP_REQUIRED',
  UNKNOWN = 'UNKNOWN',
}

export enum Sentiment {
  POSITIVE = 'POSITIVE',
  NEUTRAL = 'NEUTRAL',
  NEGATIVE = 'NEGATIVE',
  MIXED = 'MIXED',
  UNKNOWN = 'UNKNOWN',
}

export enum SalesStrategy {
  DISCOVERY = 'DISCOVERY',
  CONSULTATIVE = 'CONSULTATIVE',
  ROI = 'ROI',
  COMPETITOR_REPLACEMENT = 'COMPETITOR_REPLACEMENT',
  URGENCY = 'URGENCY',
  EDUCATIONAL = 'EDUCATIONAL',
  FAST_CLOSE = 'FAST_CLOSE',
}

export enum BudgetLevel {
  UNKNOWN = 'UNKNOWN',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CONFIRMED = 'CONFIRMED',
}

export enum AuthorityLevel {
  UNKNOWN = 'UNKNOWN',
  INFLUENCER = 'INFLUENCER',
  EVALUATOR = 'EVALUATOR',
  DECISION_MAKER = 'DECISION_MAKER',
}

export enum NeedLevel {
  UNKNOWN = 'UNKNOWN',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum TimelineLevel {
  UNKNOWN = 'UNKNOWN',
  NO_TIMELINE = 'NO_TIMELINE',
  OVER_90_DAYS = 'OVER_90_DAYS',
  WITHIN_90_DAYS = 'WITHIN_90_DAYS',
  WITHIN_30_DAYS = 'WITHIN_30_DAYS',
  IMMEDIATE = 'IMMEDIATE',
}

export enum ObjectionCategory {
  PRICE = 'PRICE',
  BUDGET = 'BUDGET',
  TIMING = 'TIMING',
  AUTHORITY = 'AUTHORITY',
  COMPETITOR = 'COMPETITOR',
  TRUST = 'TRUST',
  FEATURE_GAP = 'FEATURE_GAP',
  NOT_INTERESTED = 'NOT_INTERESTED',
  NEEDS_MORE_INFORMATION = 'NEEDS_MORE_INFORMATION',
  INTERNAL_RESOURCES = 'INTERNAL_RESOURCES',
  IMPLEMENTATION_COMPLEXITY = 'IMPLEMENTATION_COMPLEXITY',
  SECURITY = 'SECURITY',
  OTHER = 'OTHER',
}

export enum ObjectionSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum AppointmentStatus {
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  NO_SHOW = 'NO_SHOW',
  RESCHEDULED = 'RESCHEDULED',
}

export enum MeetingType {
  DISCOVERY = 'DISCOVERY',
  DEMO = 'DEMO',
  PROPOSAL = 'PROPOSAL',
  FOLLOW_UP = 'FOLLOW_UP',
  OTHER = 'OTHER',
}

export enum FollowUpType {
  CALLBACK = 'CALLBACK',
  EMAIL = 'EMAIL',
  MEETING_REMINDER = 'MEETING_REMINDER',
  OTHER = 'OTHER',
}

export enum FollowUpStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  OVERDUE = 'OVERDUE',
}

export enum ToolExecutionStatus {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
  TIMEOUT = 'TIMEOUT',
}

export enum HandoffUrgency {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum TransferType {
  COLD = 'COLD',
  WARM = 'WARM',
}

export enum JobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum CompetitorSentiment {
  POSITIVE = 'POSITIVE',
  NEUTRAL = 'NEUTRAL',
  NEGATIVE = 'NEGATIVE',
  UNKNOWN = 'UNKNOWN',
}
